name: Repository Build & Test on Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  issues: read
  pull-requests: write
  checks: write

env:
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: 'Checkout'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
 
    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: | 
          9.0.x

    - name: 'Restore external dependencies'
      run: dotnet restore

    - name: 'Build'
      id: build
      run: dotnet build --configuration Debug --no-restore

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: build-artifacts
        path: |
          bloop/bin/**
        retention-days: 5

    - name: 'Test'
      id: test
      run: dotnet test --no-build --restore --collect:"XPlat Code Coverage" --logger junit

    - name: 'Create test summary'
      uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
      with:
        paths: test/**/TestResults.xml
        show: "fail, skip"
      if: always()
